version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Franckeddy/ShoppingList/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  gitguardion:
    environment:
      GITGUARDIAN_API_KEY: cBc5dedDb30BBEFFe2c4dfE565074D3bfd905dF6f3461A29dedc81a45Ef2f68B70E87ed
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          orbs:
          ggshield: gitguardian/ggshield
          workflows:
            main:
              jobs:
                - ggshield/scan:
                    name: ggshield-scan # best practice is to name each orb job
                    base_revision: << pipeline.git.base_revision >>
                    revision: <<pipeline.git.revision>>

workflows:
  my-custom-workflow:
    jobs:
      - gitguardion
